id: A5593D4A3
title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for Saving
  Lives'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:43:17.091315
  last_modified_at: 2022-03-01 05:43:17.091318
